### ISSUE TITLE
unable to add extra ini for php

### ISSUE THREAD

**Issue by leokun** [jdeathe/centos-ssh-apache-php-fcgi#2]
Hi,

I was suprized that I can't add an extra ini file for php.
Actually, I vas able to link a ini file to `/etc/php.d/zzz-default.ini`, the phpinfo show it as Additional .ini files parsed but it doesn't use it.
I tried to turn on display_errors but no succes. the most weird thing is that this is working for jdeathe/centos-ssh-apache-php

Do you have any help for me ? 

Regards, 
Leo

ps : sorry if I made mistakes in english :-)

**Comment by jdeathe** [comment]
To make PHP configuration changes in the FastCGI version the need to be applied from within the php-wrapper script - you can see a number of default settings defined here: https://github.com/jdeathe/centos-ssh-apache-php-fcgi/blob/master/var/www/app/bin/php-wrapper#L127

To override any of these you can use the PHP_VHOST_OPTIONS parameter from your Apache VirtualHost to add to or override the defaults: https://github.com/jdeathe/centos-ssh-apache-php-fcgi/blob/master/var/www/app/bin/php-wrapper#L7

The vhost.conf is brought in from the parent Docker container where you can see there are examples of how to set the date.timezone and include_path: https://github.com/jdeathe/centos-ssh-apache-php/blob/master/var/www/app/vhost.conf#L70

You should be able to add your own settings by simply adding another `-d<php-setting>=<setting-value>`.

Please let me know if you require any further clarifications?
